# Generated by Django 5.1.3 on 2025-04-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='names',
            new_name='name',
        ),
    ]
