[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  NODE_VERSION = "18"

[context.deploy-preview.environment]
  NODE_VERSION = "18"

[context.branch-deploy.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Custom domain redirects
[[redirects]]
  from = "https://eswarsaiportfolio.org/*"
  to = "https://eswarsaiportfolio.org/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
